#' Driver A
#'
#' A vector of 10000 values (years) between 0 and 100 generated by \code{\link{simulateDriver}} with a temporal autocorrelation significant for 600 years. It is meant to be used as input for \code{\link{simulatePopulation}}
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name driverA
#' @usage data(driverA)
#' @format numeric vector of length 10000.
#' @seealso \code{\link{simulateDriver}}
"driverA"


#' Driver B
#'
#' A vector of 10000 values (years) between 0 and 100 generated by \code{\link{simulateDriver}} with a temporal autocorrelation significant for 600 years. It is meant to be used as input for \code{\link{simulatePopulation}}
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name driverB
#' @usage data(driverB)
#' @format numeric vector of length 10000.
#' @seealso \code{\link{simulateDriver}}
"driverB"


#' Drivers with different temporal autocorrelations.
#'
#' A dataframe with 60000 rows and 4 columns (years) containing two drivers (A and B) generated by \code{\link{simulateDriver}} with different temporal autocorrelations (200, 600, and 1800). It is meant to be used as input for \code{\link{simulatePopulation}}
#'
#' \itemize{
#'   \item \emph{time} integer.
#'   \item \emph{driver} character, values are \code{A} and \code{B}
#'   \item \emph{autocorrelation.length} numeric, values are 200, 600, and 1800.
#'   \item \emph{value} numeric, value of the driver for the given \emph{time}.
#' }
#'
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name drivers
#' @usage data(drivers)
#' @format numeric vector of length 10000.
#' @seealso \code{\link{simulateDriver}}
"drivers"


#' Parameters of 2 virtual taxa.
#'
#' A dataframe with 2 rows and 16 columns with the parameters of two virtual taxa. It was generated by \code{\link{parametersDataframe}} and \code{\link{fixParametersTypes}}. It is meant to be used as input for \code{\link{simulatePopulation}}. It's columns are:
#'
#' \itemize{
#'   \item label: to store names (character string) of the virtual taxa.
#'   \item maximum.age: integer, maximum possible age of the individuals in years.
#'   \item reproductive.age: integer, age of sexual maturity in years.
#'   \item fecundity: integer, number of maximum viable seeds produced by a mature individual under fully suitable conditions.
#'   \item growth.rate: numeric, parameter of the logistic growth function.
#'   \item pollen.control: numeric in the interval [0, 1]. If 0, pollen productivity depends on environmental suitability only. The larger the number, biomass takes over environmental suitability in determining pollen productivity.
#'   \item maximum.biomass: integer, maximum biomass of the individuals.
#'   \item carrying.capacity: integer, maximum sum of biomass of the individuals. Very large carrying capacities plus a low maximum.biomass generates too many individuals for the simulation to remain efficient. Try to set carrying.capacity and maximum.biomass to carrying.capacity divided by biomass returns a number lower than 1000 (and even better if it is closer to 100).
#'   \item driver.A.weight: numeric in the interval [0, 1], represents the relative influence of the driver on environmental suitability.
#'   \item driver.B.weight: numeric in the interval [0, 1], represents the relative influence of the driver on environmental suitability. The sum of weights of drivers A and B should be 1.
#'   \item niche.A.mean: numeric, in the same units as driver A. It is the mean of the normal function defining the response of the virtual taxa to driver A.
#'   \item niche.A.sd: numeric, in the same units as driver A. It is the standard deviation of the normal function defining the response of the virtual taxa to driver A.
#'   \item niche.B.mean: as above, but for driver B.
#'   \item niche.B.sd: as above, but for driver B.
#'   \item autocorrelation.length.A: numeric, only useful if several drivers generated with different autocorrelation lengths are available (and identified by the column \code{autocorrelation.length}) in the \code{drivers} argument provided to the \code{\link{simulatePopulation}} function.
#'   \item autocorrelation.length.B: same as above.
#' }
#'
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name parameters
#' @usage data(drivers)
#' @format numeric vector of length 10000.
#' @seealso \code{\link{parametersCheck}}, \code{\link{parametersDataframe}}, \code{\link{simulatePopulation}}
"parameters"


#' List with two simulation outputs.
#'
#' A list of dataframes with two slots, output of \code{\link{simulatePopulation}}. Each slot corresponds to a virtual taxon from the \code{\link{parameters}} dataframe. Each dataframe has the following columns:
#'
#' \itemize{
#'   \item \emph{Time} integer, ages in years. Negative ages indicate the burn-in period.
#'   \item \emph{Pollen} numeric, pollen counts
#'   \item \emph{Population.mature} numeric, number of mature individuals.
#'   \item \emph{Population.immatre} numeric, number of immature individuals.
#'   \item \emph{Population.viable.seeds} numeric, number of viable seeds generated each year.
#'   \item \emph{Suitability} numeric, environmental suitability computed from the driver by the normal function/s defining the taxon niche.
#'   \item \emph{Biomass.total} numeric, overall biomass of the population.
#'   \item \emph{Biomass.mature} numeric, sum of biomass of mature individuals.
#'   \item \emph{Biomass.immature} numeric, sum of biomass of immature individuals.
#'   \item \emph{Mortality.mature} numeric, number of mature individuals dead each year.
#'   \item \emph{Mortality.immature} numeric, same as above for immature individuals.
#'   \item \emph{Driver.A} numeric, values of driver A.
#'   \item \emph{Driver.B} numeric, values of driver B, if available, and NA otherwise.
#'   \item \emph{Period} qualitative, with value "Burn-in" for burn-in period, and "Simulation" otherwise.
#' }
#'
#' @author Blas M. Benito  <blasbenito@gmail.com>
#' @docType data
#' @keywords datasets
#' @name simulation
#' @usage data(simulation)
#' @format numeric vector of length 10000.
#' @seealso \code{\link{simulatePopulation}}, \code{\link{plotSimulation}}
"simulation"
